### ISSUE TITLE
The last update broke the functionality

### ISSUE THREAD

**Issue by visavi** [terrylinooo/simple-cache#13]
PHP 8.x

for version 8 PHP installs version psr/simple-cache  3.0
This version breaks compatibility

```
PHP Fatal error:  Declaration of Shieldon\SimpleCache\CacheProvider::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed
```

**Comment by Tommuh** [comment]
Having the same issue.

**Comment by terrylinooo** [comment]
I'll fix it today and add unit testing for PHP 8 for GitHub action. Thanks for reporting.

**Comment by terrylinooo** [comment]
try
```
composer update shieldon/simple-cache
```

**Comment by visavi** [comment]
version 2.0 works well with php8.x too
"psr/simple-cache": "2.0.0",

**Comment by darkvovich** [comment]
Problem still exists on PHP 8.2 and shieldon/simple-cache [1.3.3]

`Fatal error: Declaration of Shieldon\SimpleCache\CacheProvider::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed in /vendor/shieldon/simple-cache/src/SimpleCache/CacheProvider.php on line 43`

**Comment by darkvovich** [comment]
And all other
`Fatal error: Declaration of Shieldon\SimpleCache\CacheProvider::set($key, $value, $ttl = null) must be compatible with Psr\SimpleCache\CacheInterface::set(string $key, mixed $value, DateInterval|int|null $ttl = null): bool in /vendor/shieldon/simple-cache/src/SimpleCache/CacheProvider.php on line 66`
