### ISSUE TITLE
Any chance to add nginx cache?

### ISSUE THREAD

**Issue by uhlhosting** [terrylinooo/simple-cache#6]
Would be so usefull to have a all in one module that can clear cache for all system.

**Comment by terrylinooo** [comment]
Nginx cache is a cache architecture in system level, not in application.

**Comment by uhlhosting** [comment]
Yes, and thus fastcgi cache from nginnx can be monitored and purged via Wordpress. At least the optionn to purge it would be great, would take out the need to add another plugin to do that.
