### ISSUE TITLE
Checking if MySQL db has been built

### ISSUE THREAD

**Issue by S1SYPHOS** [terrylinooo/simple-cache#8]
Hey there,
I'm thinking about the `rebuild()` function, and how to check if the database was initiated before. For `sqlite`, I would simply check if `cache.sqlite3` exists, but how would I do this for MySQL?

Since `simple-cache` handles the db connection, it could provide a) a method or b) check automatically & (re)build if need be .. 

I'm grateful for any pointer in the right direction ..
S1SYPHOS

**Comment by terrylinooo** [comment]
```
SHOW TABLES LIKE 'yourtable';
```

I often use this to check if the table exists or not.

**Comment by S1SYPHOS** [comment]
Alright, thanks for getting back at me - have a nice day!
